### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by zeenix** [kinvolk/habitat-operator#131]
I'm seeing a crash on startup:

```
#  ./habitat-operator --kubeconfig /var/lib/kube-spawn/default/kubeconfig 
ts=2017-11-22T16:05:17.159334625+01:00 level=info msg="Habitat CRD already exists, continuing"
ts=2017-11-22T16:05:17.160388968+01:00 level=info component=controller msg="Watching Habitat objects"
ERROR: logging before flag.Parse: E1122 16:05:17.171033    3611 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/golang/src/runtime/asm_amd64.s:514
/usr/lib/golang/src/runtime/panic.go:489
/usr/lib/golang/src/runtime/panic.go:63
/usr/lib/golang/src/runtime/signal_unix.go:290
<autogenerated>:18
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/store.go:84
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/controller.go:258
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:710
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:330
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:215
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/controller.go:192
<autogenerated>:54
/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547
/usr/lib/golang/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12025c5]

goroutine 31 [running]:
github.com/kinvolk/habitat-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x163e140, 0x21fa3e0)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/kinvolk/habitat-operator/pkg/habitat/apis/cr/v1.(*Habitat).GetNamespace(0x0, 0x0, 0x7f155c393be8)
	<autogenerated>:18 +0x5
github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x179b160, 0x0, 0xc42011ccc0, 0xc42054ed00, 0x40cae8, 0x167c240)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/store.go:84 +0x126
github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x179b160, 0x0, 0xc42054ed80, 0x14f70c1, 0x21a8e60, 0xc42054ed70)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/controller.go:258 +0x74
github.com/kinvolk/habitat-operator/pkg/habitat/controller.(*HabitatController).enqueue(0xc4203b1ea0, 0x179b160, 0x0)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:710 +0x4d
github.com/kinvolk/habitat-operator/pkg/habitat/controller.(*HabitatController).handlePodAdd(0xc4203b1ea0, 0x17b4e80, 0xc420410c00)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:330 +0x152
github.com/kinvolk/habitat-operator/pkg/habitat/controller.(*HabitatController).(github.com/kinvolk/habitat-operator/pkg/habitat/controller.handlePodAdd)-fm(0x17b4e80, 0xc420410c00)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/pkg/habitat/controller/controller.go:215 +0x3e
github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc42039a530, 0xc42039a540, 0xc42039a550, 0x17b4e80, 0xc420410c00)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/controller.go:192 +0x49
github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc420430440, 0x17b4e80, 0xc420410c00)
	<autogenerated>:54 +0x73
github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc4202784d0, 0xc420247620)
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547 +0x2f6
created by github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run
	/home/zeenix/golang/src/github.com/kinvolk/habitat-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:402 +0xb3
```

**Comment by LiliC** [comment]
To clarify this is a "crash", not from a clean setup, which can be seen from the `"Habitat CRD already exists, continuing"`. 

If you can reproduce this issue, can you describe me the steps you took before this happened.

**Comment by zeenix** [comment]
Yes but for UX point of view, that distinction doesn't mean much since it's very easy to end up not cleanly exiting the operator currently. The steps to reproduce are simple: You run the operator, launch a pod that uses the operator and then stop and start the operator (in my case, the pod was still running).

**Comment by LiliC** [comment]
@zeenix I tried it out, from master, and I can't seem to reproduce this problem.

```
lili at Lilis-MBP in ~/go/src/github.com/kinvolk/habitat-operator on master!
○ ./habitat-operator --kubeconfig ~/.kube/config
ts=2017-11-23T11:48:37.26016666+01:00 level=info msg="created Habitat CRD"
ts=2017-11-23T11:48:37.263411097+01:00 level=info component=controller msg="Watching Habitat objects"
ts=2017-11-23T11:48:40.832642278+01:00 level=info component=controller msg="created deployment" name=example-standalone-habitat
ts=2017-11-23T11:48:40.842645248+01:00 level=info component=controller msg="created peer IP ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:40.960354656+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:41.005894823+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:41.467382568+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:42.266140545+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:43.066097807+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:43.888953708+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:44.665935412+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:45.466873416+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:46.272796165+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:47.066351708+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:47.865609768+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:48.665657624+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:49.477296993+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:50.270248263+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:51.065722378+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:51.868568998+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:52.663927384+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:53.464677286+01:00 level=info component=controller msg="removed peer IP from ConfigMap" name=peer-watch-file
ts=2017-11-23T11:48:54.269499194+01:00 level=info component=controller msg="updated peer IP in ConfigMap" name=peer-watch-file ip=172.17.0.2
^Cts=2017-11-23T11:50:07.002939979+01:00 level=info msg="received SIGTERM, exiting gracefully..."

lili at Lilis-MBP in ~/go/src/github.com/kinvolk/habitat-operator on master!
○ ./habitat-operator --kubeconfig ~/.kube/config
ts=2017-11-23T11:50:07.912225894+01:00 level=info msg="Habitat CRD already exists, continuing"
ts=2017-11-23T11:50:07.915598557+01:00 level=info component=controller msg="Watching Habitat objects"
```

Can you maybe tell which version of Kubernetes you are using and which version or commit of Habitat operator you are using?

**Comment by zeenix** [comment]
```[root@localhost habitat-operator]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost habitat-operator]# git describe 
v0.2.0
```
I meant, i had a pod up and running:

```
[root@localhost habitat-operator]# kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
testapp-2266039419-j63pv   1/1       Running   0          18h
```

**Comment by zeenix** [comment]
If you want to look into this and can't reproduce after multiple attempts, I'd suggest to look at the stack trace and investigate from there instead. Sometimes it's easy to tell why something would crash, even if you can't reproduce.

**Comment by LiliC** [comment]
@zeenix I see, you created a Habitat service. I was able to reproduce following that additional step. 👍 Will investigate to see what's happening, thanks for the report!

**Comment by dongsupark** [comment]
Just following the backtrace and reading the code, this line looks like an issue:
https://github.com/kinvolk/habitat-operator/blob/v0.2.0/pkg/habitat/controller/controller.go#L362
`hc.getHabitatFromLabeledResource(pod)` can return nil and an error together, so when calling `hc.enqueue(h)`, `h` can be nil. Then the nil object is passed all the way down to `MetaNamespaceKeyFunc()`, where it panics with nil dereference. Right?

I've not tested it at all though.

**Comment by LiliC** [comment]
Yes, I found that yesterday as well, have a branch for the temporary fix. Zeeshan tested it, and it solved his problem.

But I came across another similar panic, while trying to reproduce the original problem, when the `hab` object was not nil. So I want to investigate to see why that happened. Might be a cache issue, will try to reproduce it.
